//Entry point for loading any css/libraries.
//Makes app.bundle.js smaller to ease debugging as well.
import 'angular-material/angular-material.css'
import 'font-awesome/css/font-awesome.css'
import 'office-ui-fabric-core/dist/css/fabric.css'
import 'ui-select/dist/select.css'
import 'angular-loading-bar/build/loading-bar.css'

import 'core-js'
import 'whatwg-fetch'
import 'bluebird'
import 'lodash'
import 'moment'
import 'urijs'

import 'angular'
import 'angular-animate'
import 'angular-sanitize'
import 'angular-ui-router'
import 'angular-material'
import 'angular-ui-grid/ui-grid.js'
import 'angular-ui-grid/ui-grid.css'
import 'angular-ui-grid/ui-grid.woff'
import 'angular-ui-grid/ui-grid.svg'
import 'angular-loading-bar'
import 'angular-vs-repeat'
import 'ng-file-upload'
import 'ngclipboard'
import 'angular-resizable'
import 'ui-select'